/**
 * Test fixtures for Hotel Risk Pro analysis engine
 */

// Fixture 1: Strongly insured hotel
const stronglyInsuredHotel = {
  hotelProfile: {
    hotelName: 'Grand Plaza Hotel',
    address: '123 Main Street',
    city: 'Denver',
    state: 'CO',
    zip: '80202',
    numberOfRooms: 120,
    squareFootage: 85000,
    yearBuilt: 2010,
    yearRenovated: 2020,
    numberOfFloors: 8,
    constructionType: 'concrete',
    roofType: 'membrane',
    roofAge: 4,
    sprinklerStatus: 'yes',
    fireAlarmStatus: 'yes',
    hasPoolSpa: true,
    hasRestaurantBar: true,
    hasEventSpace: true,
    hasParkingStructureOrValet: false,
  },
  financialProfile: {
    annualGrossRevenue: 8400000,
    roomRevenuePct: 70,
    foodBeverageRevenuePct: 20,
    eventRevenuePct: 8,
    otherRevenuePct: 2,
    averageOccupancy: 75,
    adr: 185,
    revpar: 139,
    fixedMonthlyOperatingCosts: 180000,
    monthlyPayrollBurden: 220000,
    monthlyDebtService: 50000,
    emergencyCashReserves: 800000,
  },
  policyProfile: {
    carrier: 'Travelers',
    policyPeriodStart: '2025-01-01',
    policyPeriodEnd: '2026-01-01',
    propertyLimit: 32000000,
    businessInterruptionLimit: 12000000,
    extraExpenseLimit: 2000000,
    liabilityLimit: 3000000,
    umbrellaLimit: 5000000,
    deductible: 25000,
    biWaitingPeriodDays: 3,
    biRestorationPeriodMonths: 18,
    coinsurancePct: 90,
    ordinanceLawCoverage: 5000000,
    equipmentBreakdownCoverage: true,
    floodCoverage: 0,
    windCoverage: 32000000,
    sewerBackupCoverage: 500000,
    namedExclusions: [],
    sublimits: [],
    scheduledCoverages: [],
  },
  lossRuns: [
    {
      claimYear: 2023,
      claimDate: '2023-06-15',
      claimType: 'Property',
      causeOfLoss: 'Hail damage to roof',
      amountPaid: 45000,
      reserveAmount: 0,
      status: 'Closed',
      propertyAreaAffected: 'Roof - west section',
      notes: 'Minor hail damage, repaired',
    },
  ],
  operationalRiskProfile: {
    knownMaintenanceIssues: [],
    priorRoofLeaks: false,
    hvacIssues: false,
    plumbingIssues: false,
    electricalIssues: false,
    moldMoistureHistory: false,
    securityIncidents: false,
    frequentSlipFallIssues: false,
    crimeConcerns: false,
    deferredMaintenance: false,
    inspectionDeficiencies: false,
    codeComplianceIssues: false,
    completedMitigationProjects: ['Roof replacement 2020'],
    unresolvedMitigationNeeds: [],
  },
  hazardProfile: {
    floodZone: 'x',
    coastalWindExposure: false,
    wildfireExposure: false,
    freezeExposure: true,
    stormHailExposure: true,
    crimeLevel: 'low',
    utilityInterruptionRisk: false,
    contractorScarcity: false,
    litigationSensitivity: 'low',
  },
};

// Fixture 2: Property-underinsured hotel
const propertyUnderinsuredHotel = {
  hotelProfile: {
    hotelName: 'Historic Riverside Inn',
    address: '456 River Road',
    city: 'Charleston',
    state: 'SC',
    zip: '29401',
    numberOfRooms: 85,
    squareFootage: 62000,
    yearBuilt: 1925,
    yearRenovated: 2005,
    numberOfFloors: 4,
    constructionType: 'masonry',
    roofType: 'tile',
    roofAge: 19,
    sprinklerStatus: 'partial',
    fireAlarmStatus: 'yes',
    hasPoolSpa: false,
    hasRestaurantBar: true,
    hasEventSpace: false,
    hasParkingStructureOrValet: false,
  },
  financialProfile: {
    annualGrossRevenue: 5200000,
    roomRevenuePct: 75,
    foodBeverageRevenuePct: 22,
    eventRevenuePct: 0,
    otherRevenuePct: 3,
    averageOccupancy: 68,
    adr: 165,
    fixedMonthlyOperatingCosts: 120000,
    monthlyPayrollBurden: 140000,
    monthlyDebtService: 35000,
    emergencyCashReserves: 250000,
  },
  policyProfile: {
    carrier: 'Hartford',
    policyPeriodStart: '2025-06-01',
    policyPeriodEnd: '2026-06-01',
    propertyLimit: 14000000,
    businessInterruptionLimit: 6000000,
    extraExpenseLimit: 500000,
    liabilityLimit: 2000000,
    umbrellaLimit: 0,
    deductible: 50000,
    biWaitingPeriodDays: 7,
    biRestorationPeriodMonths: 12,
    coinsurancePct: 80,
    ordinanceLawCoverage: 0,
    equipmentBreakdownCoverage: false,
    floodCoverage: 0,
    windCoverage: 14000000,
    sewerBackupCoverage: 100000,
    namedExclusions: [],
    sublimits: [],
    scheduledCoverages: [],
  },
  lossRuns: [],
  operationalRiskProfile: {
    knownMaintenanceIssues: [],
    priorRoofLeaks: false,
    hvacIssues: false,
    plumbingIssues: false,
    electricalIssues: false,
    moldMoistureHistory: false,
    deferredMaintenance: false,
    inspectionDeficiencies: false,
  },
  hazardProfile: {
    floodZone: 'ae',
    coastalWindExposure: true,
    wildfireExposure: false,
    stormHailExposure: true,
    crimeLevel: 'low',
    contractorScarcity: false,
    litigationSensitivity: 'moderate',
  },
};

// Fixture 3: BI-shortfall hotel
const biShortfallHotel = {
  hotelProfile: {
    hotelName: 'Mountain View Resort',
    address: '789 Summit Drive',
    city: 'Aspen',
    state: 'CO',
    zip: '81611',
    numberOfRooms: 145,
    squareFootage: 110000,
    yearBuilt: 1998,
    yearRenovated: 2018,
    numberOfFloors: 6,
    constructionType: 'wood',
    roofType: 'shingle',
    roofAge: 6,
    sprinklerStatus: 'yes',
    fireAlarmStatus: 'yes',
    hasPoolSpa: true,
    hasRestaurantBar: true,
    hasEventSpace: true,
    hasParkingStructureOrValet: true,
  },
  financialProfile: {
    annualGrossRevenue: 14500000,
    roomRevenuePct: 65,
    foodBeverageRevenuePct: 25,
    eventRevenuePct: 8,
    otherRevenuePct: 2,
    averageOccupancy: 82,
    adr: 295,
    fixedMonthlyOperatingCosts: 320000,
    monthlyPayrollBurden: 380000,
    monthlyDebtService: 95000,
    emergencyCashReserves: 1200000,
  },
  policyProfile: {
    carrier: 'Chubb',
    policyPeriodStart: '2025-03-01',
    policyPeriodEnd: '2026-03-01',
    propertyLimit: 45000000,
    businessInterruptionLimit: 4000000,
    extraExpenseLimit: 1000000,
    liabilityLimit: 5000000,
    umbrellaLimit: 10000000,
    deductible: 75000,
    biWaitingPeriodDays: 5,
    biRestorationPeriodMonths: 12,
    coinsurancePct: 90,
    ordinanceLawCoverage: 8000000,
    equipmentBreakdownCoverage: true,
    floodCoverage: 0,
    windCoverage: 45000000,
    sewerBackupCoverage: 250000,
    namedExclusions: [],
    sublimits: [],
    scheduledCoverages: [],
  },
  lossRuns: [],
  operationalRiskProfile: {
    priorRoofLeaks: false,
    hvacIssues: false,
    plumbingIssues: false,
    deferredMaintenance: false,
    inspectionDeficiencies: false,
  },
  hazardProfile: {
    floodZone: 'x',
    coastalWindExposure: false,
    wildfireExposure: true,
    stormHailExposure: false,
    crimeLevel: 'low',
    contractorScarcity: true,
    litigationSensitivity: 'low',
  },
};

// Fixture 4: Repeated-water-loss hotel
const repeatedWaterLossHotel = {
  hotelProfile: {
    hotelName: 'Bayside Inn',
    address: '321 Harbor View',
    city: 'Seattle',
    state: 'WA',
    zip: '98101',
    numberOfRooms: 95,
    squareFootage: 68000,
    yearBuilt: 1985,
    yearRenovated: null,
    numberOfFloors: 5,
    constructionType: 'concrete',
    roofType: 'membrane',
    roofAge: 22,
    sprinklerStatus: 'yes',
    fireAlarmStatus: 'yes',
    hasPoolSpa: false,
    hasRestaurantBar: true,
    hasEventSpace: false,
    hasParkingStructureOrValet: false,
  },
  financialProfile: {
    annualGrossRevenue: 6200000,
    roomRevenuePct: 78,
    foodBeverageRevenuePct: 18,
    eventRevenuePct: 0,
    otherRevenuePct: 4,
    fixedMonthlyOperatingCosts: 145000,
    monthlyPayrollBurden: 165000,
    monthlyDebtService: 28000,
    emergencyCashReserves: 320000,
  },
  policyProfile: {
    carrier: 'Liberty Mutual',
    policyPeriodStart: '2025-09-01',
    policyPeriodEnd: '2026-09-01',
    propertyLimit: 24000000,
    businessInterruptionLimit: 7000000,
    liabilityLimit: 2000000,
    umbrellaLimit: 3000000,
    deductible: 35000,
    biWaitingPeriodDays: 5,
    biRestorationPeriodMonths: 12,
    coinsurancePct: 80,
    ordinanceLawCoverage: 2000000,
    equipmentBreakdownCoverage: true,
    floodCoverage: 0,
    windCoverage: 24000000,
    sewerBackupCoverage: 250000,
    namedExclusions: [],
    sublimits: [],
    scheduledCoverages: [],
  },
  lossRuns: [
    {
      claimYear: 2024,
      claimType: 'Water',
      causeOfLoss: 'Roof leak - 4th floor',
      amountPaid: 85000,
      status: 'Closed',
      propertyAreaAffected: '4th floor east wing',
    },
    {
      claimYear: 2023,
      claimType: 'Water',
      causeOfLoss: 'Pipe burst - 3rd floor',
      amountPaid: 62000,
      status: 'Closed',
      propertyAreaAffected: '3rd floor',
    },
    {
      claimYear: 2022,
      claimType: 'Water',
      causeOfLoss: 'Roof leak - multiple areas',
      amountPaid: 125000,
      status: 'Closed',
      propertyAreaAffected: 'Multiple floors',
    },
    {
      claimYear: 2024,
      claimType: 'Liability',
      causeOfLoss: 'Slip and fall - lobby',
      amountPaid: 15000,
      status: 'Open',
      propertyAreaAffected: 'Lobby',
    },
  ],
  operationalRiskProfile: {
    priorRoofLeaks: true,
    hvacIssues: false,
    plumbingIssues: true,
    electricalIssues: false,
    moldMoistureHistory: true,
    deferredMaintenance: true,
    inspectionDeficiencies: false,
  },
  hazardProfile: {
    floodZone: 'x',
    coastalWindExposure: false,
    wildfireExposure: false,
    stormHailExposure: true,
    crimeLevel: 'moderate',
    contractorScarcity: false,
    litigationSensitivity: 'moderate',
  },
};

// Fixture 5: Partial-data hotel
const partialDataHotel = {
  hotelProfile: {
    hotelName: 'Budget Stay Motel',
    address: '555 Highway 50',
    city: 'Phoenix',
    state: 'AZ',
    zip: '85001',
    numberOfRooms: 48,
    squareFootage: null,
    yearBuilt: null,
    yearRenovated: null,
    constructionType: null,
    roofAge: null,
    sprinklerStatus: 'no',
    fireAlarmStatus: 'yes',
    hasPoolSpa: true,
    hasRestaurantBar: false,
    hasEventSpace: false,
    hasParkingStructureOrValet: false,
  },
  financialProfile: {
    annualGrossRevenue: 1800000,
    roomRevenuePct: 95,
    foodBeverageRevenuePct: 0,
    eventRevenuePct: 0,
    otherRevenuePct: 5,
    fixedMonthlyOperatingCosts: null,
    monthlyPayrollBurden: null,
    monthlyDebtService: null,
    emergencyCashReserves: null,
  },
  policyProfile: {
    carrier: 'State Farm',
    propertyLimit: 5000000,
    businessInterruptionLimit: 2000000,
    liabilityLimit: 1000000,
    umbrellaLimit: 0,
    deductible: 10000,
    biWaitingPeriodDays: null,
    biRestorationPeriodMonths: null,
    coinsurancePct: null,
    ordinanceLawCoverage: null,
    equipmentBreakdownCoverage: null,
    floodCoverage: null,
    windCoverage: null,
    sewerBackupCoverage: null,
    namedExclusions: [],
    sublimits: [],
    scheduledCoverages: [],
  },
  lossRuns: [],
  operationalRiskProfile: {},
  hazardProfile: {
    floodZone: 'unknown',
    wildfireExposure: false,
    crimeLevel: 'moderate',
  },
};

// Fixture 6: Critical-risk hotel (multiple issues)
const criticalRiskHotel = {
  hotelProfile: {
    hotelName: 'Coastal Beach Resort',
    address: '100 Ocean Drive',
    city: 'Miami Beach',
    state: 'FL',
    zip: '33139',
    numberOfRooms: 200,
    squareFootage: 145000,
    yearBuilt: 1965,
    yearRenovated: 1995,
    numberOfFloors: 12,
    constructionType: 'concrete',
    roofType: 'flat',
    roofAge: 29,
    sprinklerStatus: 'partial',
    fireAlarmStatus: 'yes',
    hasPoolSpa: true,
    hasRestaurantBar: true,
    hasEventSpace: true,
    hasParkingStructureOrValet: true,
  },
  financialProfile: {
    annualGrossRevenue: 18000000,
    roomRevenuePct: 60,
    foodBeverageRevenuePct: 28,
    eventRevenuePct: 10,
    otherRevenuePct: 2,
    averageOccupancy: 72,
    adr: 285,
    fixedMonthlyOperatingCosts: 420000,
    monthlyPayrollBurden: 510000,
    monthlyDebtService: 125000,
    emergencyCashReserves: 450000,
  },
  policyProfile: {
    carrier: 'Various',
    policyPeriodStart: '2025-01-01',
    policyPeriodEnd: '2026-01-01',
    propertyLimit: 28000000,
    businessInterruptionLimit: 5000000,
    extraExpenseLimit: 750000,
    liabilityLimit: 1500000,
    umbrellaLimit: 2000000,
    deductible: 150000,
    biWaitingPeriodDays: 14,
    biRestorationPeriodMonths: 12,
    coinsurancePct: 90,
    ordinanceLawCoverage: 0,
    equipmentBreakdownCoverage: false,
    floodCoverage: 0,
    windCoverage: 28000000,
    sewerBackupCoverage: 100000,
    namedExclusions: ['Mold', 'Flood'],
    sublimits: [],
    scheduledCoverages: [],
  },
  lossRuns: [
    {
      claimYear: 2024,
      claimType: 'Water',
      causeOfLoss: 'Hurricane-related water intrusion',
      amountPaid: 285000,
      status: 'Open',
      propertyAreaAffected: 'Multiple floors',
    },
    {
      claimYear: 2023,
      claimType: 'Water',
      causeOfLoss: 'Roof leak',
      amountPaid: 145000,
      status: 'Closed',
      propertyAreaAffected: 'Top floor',
    },
    {
      claimYear: 2023,
      claimType: 'Liability',
      causeOfLoss: 'Pool injury',
      amountPaid: 425000,
      status: 'Closed',
      propertyAreaAffected: 'Pool area',
    },
    {
      claimYear: 2022,
      claimType: 'Wind',
      causeOfLoss: 'Hurricane damage',
      amountPaid: 520000,
      status: 'Closed',
      propertyAreaAffected: 'Exterior and roof',
    },
    {
      claimYear: 2021,
      claimType: 'Water',
      causeOfLoss: 'Plumbing failure',
      amountPaid: 95000,
      status: 'Closed',
      propertyAreaAffected: '2nd floor',
    },
  ],
  operationalRiskProfile: {
    priorRoofLeaks: true,
    hvacIssues: true,
    plumbingIssues: true,
    electricalIssues: false,
    moldMoistureHistory: true,
    deferredMaintenance: true,
    inspectionDeficiencies: true,
    codeComplianceIssues: true,
  },
  hazardProfile: {
    floodZone: 'ae',
    coastalWindExposure: true,
    wildfireExposure: false,
    stormHailExposure: true,
    crimeLevel: 'moderate',
    contractorScarcity: true,
    litigationSensitivity: 'high',
  },
};

module.exports = {
  stronglyInsuredHotel,
  propertyUnderinsuredHotel,
  biShortfallHotel,
  repeatedWaterLossHotel,
  partialDataHotel,
  criticalRiskHotel,
};
